using System;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Xml.Linq;
using SEP.App.Models;
using SEP.App.Resources;

namespace SEP.App.Services;

/// <summary>Creates and decommissions project folders in a library, then lets the catalog rescan that library.</summary>
public class E3dProjectService : IE3dProjectService
{
    private readonly IProjectCatalog _catalog;

    public E3dProjectService(IProjectCatalog catalog)
    {
        _catalog = catalog;
    }

    public async Task<(bool Success, string Message)> CreateProjectAsync(string code, string name, string rootDir, string? templateDir = null)
    {
        code = (code ?? string.Empty).Trim().ToUpperInvariant();
        name = string.IsNullOrWhiteSpace(name) ? code : name.Trim();

        if (code.Length < 2 || code.Length > 5 || !Regex.IsMatch(code, "^[A-Z0-9]+$"))
        {
            return (false, Strings.Create_InvalidCode);
        }

        string root = SepPaths.Normalize(string.IsNullOrWhiteSpace(rootDir) ? _catalog.LocalProjectsDir : rootDir);
        string targetDir = Path.Combine(root, code);

        var result = await Task.Run(() =>
        {
            try
            {
                Directory.CreateDirectory(targetDir);
                string lc = code.ToLowerInvariant();

                string[] subdirs = {
                    $"{lc}000", $"{lc}iso", $"{lc}dwg", $"{lc}mac", $"{lc}pic",
                    $"{lc}dflts", $"{lc}dia", $"{lc}etm", $"{lc}gcd", $"{lc}info",
                    $"{lc}psi", $"{lc}ste", $"{lc}tpl"
                };

                foreach (var sub in subdirs)
                {
                    Directory.CreateDirectory(Path.Combine(targetDir, sub));
                }

                // Clone from template if provided
                if (!string.IsNullOrEmpty(templateDir) && Directory.Exists(templateDir))
                {
                    foreach (var srcSub in Directory.GetDirectories(templateDir))
                    {
                        string subName = Path.GetFileName(srcSub);
                        if (subName.ToLowerInvariant().EndsWith("000"))
                        {
                            string dest000 = Path.Combine(targetDir, $"{lc}000");
                            CopyDirectory(srcSub, dest000);
                        }
                    }
                }

                // Generate evars{code}.bat
                string evarsBat = Path.Combine(targetDir, $"evars{code}.bat");
                string evarsContent = $@"rem   AVEVA Everything3D Project Environment: {code}
rem   Generated by SEP (Smart E3D Platform)
rem ------------------------------------------------------------
SET {code}000=%projects_dir%{code}\{lc}000
SET {code}ISO=%projects_dir%{code}\{lc}iso
SET {code}MAC=%projects_dir%{code}\{lc}mac
SET {code}PIC=%projects_dir%{code}\{lc}pic
SET {code}DFLTS=%projects_dir%{code}\{lc}dflts
SET {code}STE=%projects_dir%{code}\{lc}ste
SET {code}TPL=%projects_dir%{code}\{lc}tpl
SET {code}DIA=%projects_dir%{code}\{lc}dia
SET {code}INFO=%projects_dir%{code}\{lc}info
SET {code}PSI=%projects_dir%{code}\{lc}psi
SET {code}GCD=%projects_dir%{code}\{lc}gcd
SET {code}DATA=%projects_dir%{code}\{lc}dflts\Data\
SET {code}DWG=%projects_dir%{code}\{lc}dwg
SET {code}ETM=%projects_dir%{code}\{lc}etm
SET {code}000ID={code}
";
                File.WriteAllText(evarsBat, evarsContent, SepPaths.Gbk);

                // Register to ProjectInfo.xml & projects.ini
                RegisterToProjectInfoXml(root, code, name, targetDir);
                RegisterToProjectsIni(code, name, targetDir);

                return (true, string.Format(Strings.Create_Success, code));
            }
            catch (Exception ex)
            {
                return (false, string.Format(Strings.Create_Failed, ex.Message));
            }
        });

        if (result.Item1) await RefreshLibraryForAsync(root);
        return result;
    }

    public async Task<(bool Success, string Message)> DecommissionProjectAsync(ProjectItem project, string archiveDir, bool doArchive, bool doDelete)
    {
        string projectPath = project.ProjectDir;
        if (!Directory.Exists(projectPath))
            return (false, Strings.Decommission_DirMissing);

        string code = project.Code ?? project.Name.ToUpperInvariant();

        var result = await Task.Run(() =>
        {
            try
            {
                // Check locks
                var locks = Directory.GetFiles(projectPath, "*.lck", SearchOption.AllDirectories);
                if (locks.Length > 0)
                {
                    return (false, string.Format(Strings.Decommission_LocksFound, locks.Length));
                }

                // Archive
                if (doArchive)
                {
                    Directory.CreateDirectory(archiveDir);
                    string ts = DateTime.Now.ToString("yyyyMMdd_HHmmss");
                    string zipFile = Path.Combine(archiveDir, $"{project.Name}_Backup_{ts}.zip");
                    ZipFile.CreateFromDirectory(projectPath, zipFile);
                }

                // Unregister
                string parentDir = Path.GetDirectoryName(projectPath) ?? "";
                UnregisterFromProjectInfoXml(parentDir, code);
                UnregisterFromProjectsIni(code);

                // Delete physical files if requested
                if (doDelete)
                {
                    Directory.Delete(projectPath, true);
                }

                return (true, string.Format(Strings.Decommission_Success, project.Name));
            }
            catch (Exception ex)
            {
                return (false, string.Format(Strings.Decommission_Failed, ex.Message));
            }
        });

        if (result.Item1) await _catalog.RescanLibraryAsync(project.LibraryId);
        return result;
    }

    /// <summary>After creating a project: rescan the library that owns <paramref name="root"/>, or register the folder as a new library.</summary>
    private async Task RefreshLibraryForAsync(string root)
    {
        var lib = _catalog.Libraries.FirstOrDefault(l => string.Equals(l.Path, root, StringComparison.OrdinalIgnoreCase));
        if (lib != null) await _catalog.RescanLibraryAsync(lib.Id);
        else await _catalog.AddLibraryAsync(root);
    }

    public void OpenFolder(string path)
    {
        if (string.IsNullOrWhiteSpace(path)) return;
        try
        {
            if (Directory.Exists(path))
            {
                Process.Start(new ProcessStartInfo("explorer.exe", path) { UseShellExecute = true });
            }
            else if (File.Exists(path))
            {
                Process.Start(new ProcessStartInfo("explorer.exe", $"/select,\"{path}\"") { UseShellExecute = true });
            }
        }
        catch { }
    }

    private static void CopyDirectory(string src, string dest)
    {
        Directory.CreateDirectory(dest);
        foreach (var f in Directory.GetFiles(src))
        {
            File.Copy(f, Path.Combine(dest, Path.GetFileName(f)), true);
        }
        foreach (var d in Directory.GetDirectories(src))
        {
            CopyDirectory(d, Path.Combine(dest, Path.GetFileName(d)));
        }
    }

    private static void RegisterToProjectInfoXml(string projectsDir, string code, string name, string address)
    {
        try
        {
            string xmlPath = Path.Combine(projectsDir, "ProjectInfo.xml");
            if (!File.Exists(xmlPath)) return;

            var doc = XDocument.Load(xmlPath);
            var root = doc.Root;
            if (root == null) return;

            XNamespace ns = root.GetDefaultNamespace();

            // Remove existing project element if exists
            var existing = root.Elements(ns + "Project")
                .FirstOrDefault(p => (string?)p.Element(ns + "Code") == code || (string?)p.Element(ns + "Project") == code);

            if (existing != null)
            {
                existing.Element(ns + "Address")?.SetValue(address);
                existing.Element(ns + "Name")?.SetValue(name);
                existing.Element(ns + "Description")?.SetValue(name);
            }
            else
            {
                var newProj = new XElement(ns + "Project",
                    new XElement(ns + "Project", code),
                    new XElement(ns + "Code", code),
                    new XElement(ns + "Address", address),
                    new XElement(ns + "Number", code),
                    new XElement(ns + "Name", name),
                    new XElement(ns + "Description", name),
                    new XElement(ns + "Message", ""),
                    new XElement(ns + "ApplicationType", "false")
                );
                root.Add(newProj);
            }

            doc.Save(xmlPath);
        }
        catch { }
    }

    private static void UnregisterFromProjectInfoXml(string projectsDir, string code)
    {
        try
        {
            string xmlPath = Path.Combine(projectsDir, "ProjectInfo.xml");
            if (!File.Exists(xmlPath)) return;

            var doc = XDocument.Load(xmlPath);
            var root = doc.Root;
            if (root == null) return;

            XNamespace ns = root.GetDefaultNamespace();
            var targets = root.Elements(ns + "Project")
                .Where(p => string.Equals((string?)p.Element(ns + "Code"), code, StringComparison.OrdinalIgnoreCase) ||
                            string.Equals((string?)p.Element(ns + "Project"), code, StringComparison.OrdinalIgnoreCase))
                .ToList();

            foreach (var t in targets) t.Remove();
            doc.Save(xmlPath);
        }
        catch { }
    }

    private static void RegisterToProjectsIni(string code, string name, string address)
    {
        try
        {
            string? iniPath = FindProjectsIniPath();
            if (string.IsNullOrEmpty(iniPath) || !File.Exists(iniPath)) return;

            string content = File.ReadAllText(iniPath, SepPaths.Gbk);
            string sectionHeader = $"[{code}]";

            if (content.IndexOf(sectionHeader, StringComparison.OrdinalIgnoreCase) >= 0)
            {
                // Update
                string pattern = $@"\[{code}\][^\[]*";
                string replacement = $"[{code}]\r\nPATH = {address}\r\nNAME = {name}\r\nDESCRIPTION = {name}\r\n\r\n";
                content = Regex.Replace(content, pattern, replacement, RegexOptions.IgnoreCase);
            }
            else
            {
                content += $"\r\n\r\n[{code}]\r\nPATH = {address}\r\nNAME = {name}\r\nDESCRIPTION = {name}\r\n";
            }

            File.WriteAllText(iniPath, content, SepPaths.Gbk);
        }
        catch { }
    }

    private static void UnregisterFromProjectsIni(string code)
    {
        try
        {
            string? iniPath = FindProjectsIniPath();
            if (string.IsNullOrEmpty(iniPath) || !File.Exists(iniPath)) return;

            string content = File.ReadAllText(iniPath, SepPaths.Gbk);
            string pattern = $@"\[{code}\][^\[]*";
            content = Regex.Replace(content, pattern, "", RegexOptions.IgnoreCase);
            File.WriteAllText(iniPath, content, SepPaths.Gbk);
        }
        catch { }
    }

    private static string? FindProjectsIniPath()
    {
        string[] envs = { "AVEVA_DESIGN_PROJECT_DIRS", "E3D_PROJECT_DIRS", "PDMSWK" };
        foreach (var env in envs)
        {
            string? val = Environment.GetEnvironmentVariable(env);
            if (!string.IsNullOrEmpty(val))
            {
                string cand = Path.Combine(val, "projects.ini");
                if (File.Exists(cand)) return cand;
            }
        }
        string[] defaults = { @"D:\AVEVA\Projects\projects.ini", @"C:\AVEVA\Projects\projects.ini" };
        return defaults.FirstOrDefault(File.Exists);
    }
}
