//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP.App.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SEP.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SEP startup error.
        /// </summary>
        public static string App_FatalTitle {
            get {
                return ResourceManager.GetString("App_FatalTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [SEP fatal startup error] {0}  Details were written to sep_debug.log.
        /// </summary>
        public static string App_FatalBody {
            get {
                return ResourceManager.GetString("App_FatalBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SEP error.
        /// </summary>
        public static string App_UiErrorTitle {
            get {
                return ResourceManager.GetString("App_UiErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [SEP UI exception] {0}  Details were written to sep_debug.log.
        /// </summary>
        public static string App_UiErrorBody {
            get {
                return ResourceManager.GetString("App_UiErrorBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Startup failed: {0} {1}.
        /// </summary>
        public static string App_StartupFailed {
            get {
                return ResourceManager.GetString("App_StartupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Common_Ready {
            get {
                return ResourceManager.GetString("Common_Ready", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SEP · AVEVA E3D Project Manager.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active project: .
        /// </summary>
        public static string Main_ActiveProjectLabel {
            get {
                return ResourceManager.GetString("Main_ActiveProjectLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🚀 Launch E3D now.
        /// </summary>
        public static string Main_LaunchButton {
            get {
                return ResourceManager.GetString("Main_LaunchButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch to the active project and launch E3D.
        /// </summary>
        public static string Main_LaunchTooltip {
            get {
                return ResourceManager.GetString("Main_LaunchTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project Workbench.
        /// </summary>
        public static string Nav_Projects {
            get {
                return ResourceManager.GetString("Nav_Projects", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users &amp; Permissions.
        /// </summary>
        public static string Nav_UserAdmin {
            get {
                return ResourceManager.GetString("Nav_UserAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Health Check.
        /// </summary>
        public static string Nav_Diagnostics {
            get {
                return ResourceManager.GetString("Nav_Diagnostics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System &amp; Path Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No active project.
        /// </summary>
        public static string Main_NoActiveProject {
            get {
                return ResourceManager.GetString("Main_NoActiveProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No active project selected.
        /// </summary>
        public static string Main_NoActiveProjectSet {
            get {
                return ResourceManager.GetString("Main_NoActiveProjectSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not selected.
        /// </summary>
        public static string Main_StatusPending {
            get {
                return ResourceManager.GetString("Main_StatusPending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a project in the Project Workbench first..
        /// </summary>
        public static string Main_SelectProjectFirst {
            get {
                return ResourceManager.GetString("Main_SelectProjectFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switching environment and launching AVEVA E3D [{0}]....
        /// </summary>
        public static string Main_SwitchingAndLaunching {
            get {
                return ResourceManager.GetString("Main_SwitchingAndLaunching", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Projects_FilterAll {
            get {
                return ResourceManager.GetString("Projects_FilterAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 💻 Local.
        /// </summary>
        public static string Projects_FilterLocal {
            get {
                return ResourceManager.GetString("Projects_FilterLocal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🌐 Network.
        /// </summary>
        public static string Projects_FilterUnc {
            get {
                return ResourceManager.GetString("Projects_FilterUnc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search code or path....
        /// </summary>
        public static string Projects_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Projects_SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✨ New project.
        /// </summary>
        public static string Projects_CreateButton {
            get {
                return ResourceManager.GetString("Projects_CreateButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh project list.
        /// </summary>
        public static string Projects_RefreshTooltip {
            get {
                return ResourceManager.GetString("Projects_RefreshTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string Projects_OpenFolderTooltip {
            get {
                return ResourceManager.GetString("Projects_OpenFolderTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ● Active project.
        /// </summary>
        public static string Projects_ActiveBadge {
            get {
                return ResourceManager.GetString("Projects_ActiveBadge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🚀 Switch &amp; launch E3D.
        /// </summary>
        public static string Projects_SwitchAndLaunch {
            get {
                return ResourceManager.GetString("Projects_SwitchAndLaunch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decommission &amp; manage.
        /// </summary>
        public static string Projects_MoreTooltip {
            get {
                return ResourceManager.GetString("Projects_MoreTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanning E3D projects and lock status....
        /// </summary>
        public static string Projects_Scanning {
            get {
                return ResourceManager.GetString("Projects_Scanning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project scan failed: {0}.
        /// </summary>
        public static string Projects_ScanError {
            get {
                return ResourceManager.GetString("Projects_ScanError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switching active project to [{0}] and launching E3D....
        /// </summary>
        public static string Projects_SwitchingTo {
            get {
                return ResourceManager.GetString("Projects_SwitchingTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ⚠ Active database lock.
        /// </summary>
        public static string Project_LockActive {
            get {
                return ResourceManager.GetString("Project_LockActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✓ No locks.
        /// </summary>
        public static string Project_LockFree {
            get {
                return ResourceManager.GetString("Project_LockFree", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Project_SourceLocal {
            get {
                return ResourceManager.GetString("Project_SourceLocal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network (UNC).
        /// </summary>
        public static string Project_SourceUnc {
            get {
                return ResourceManager.GetString("Project_SourceUnc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ★ My projects.
        /// </summary>
        public static string Projects_FilterMine {
            get {
                return ResourceManager.GetString("Projects_FilterMine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} project(s) in {1} library(ies).
        /// </summary>
        public static string Projects_Loaded {
            get {
                return ResourceManager.GetString("Projects_Loaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scan complete: {0} project(s); {1} library(ies) unreachable (cached results shown).
        /// </summary>
        public static string Projects_ScanDone {
            get {
                return ResourceManager.GetString("Projects_ScanDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to cached.
        /// </summary>
        public static string Project_Cached {
            get {
                return ResourceManager.GetString("Project_Cached", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add to my projects.
        /// </summary>
        public static string Project_AddToMine {
            get {
                return ResourceManager.GetString("Project_AddToMine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove from my projects.
        /// </summary>
        public static string Project_RemoveFromMine {
            get {
                return ResourceManager.GetString("Project_RemoveFromMine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a library: folder, \\server\share or evarsXXX.bat.
        /// </summary>
        public static string Lib_AddPlaceholder {
            get {
                return ResourceManager.GetString("Lib_AddPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ➕ Add library.
        /// </summary>
        public static string Lib_AddButton {
            get {
                return ResourceManager.GetString("Lib_AddButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rescan this library.
        /// </summary>
        public static string Lib_Rescan {
            get {
                return ResourceManager.GetString("Lib_Rescan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove library from the list (nothing is deleted on disk).
        /// </summary>
        public static string Lib_Remove {
            get {
                return ResourceManager.GetString("Lib_Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ▶ Load whole library.
        /// </summary>
        public static string Lib_LoadWhole {
            get {
                return ResourceManager.GetString("Lib_LoadWhole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string Lib_OpenFolder {
            get {
                return ResourceManager.GetString("Lib_OpenFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to scanning….
        /// </summary>
        public static string Lib_Scanning {
            get {
                return ResourceManager.GetString("Lib_Scanning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} project(s).
        /// </summary>
        public static string Lib_ProjectsCount {
            get {
                return ResourceManager.GetString("Lib_ProjectsCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to scanned {0}.
        /// </summary>
        public static string Lib_ScannedAt {
            get {
                return ResourceManager.GetString("Lib_ScannedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to unreachable – showing cached results.
        /// </summary>
        public static string Lib_CachedResults {
            get {
                return ResourceManager.GetString("Lib_CachedResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Lib_TypeCollection {
            get {
                return ResourceManager.GetString("Lib_TypeCollection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Single project.
        /// </summary>
        public static string Lib_TypeProject {
            get {
                return ResourceManager.GetString("Lib_TypeProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library [{0}] added with {1} project(s)..
        /// </summary>
        public static string Lib_Added {
            get {
                return ResourceManager.GetString("Lib_Added", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot add library: {0}.
        /// </summary>
        public static string Lib_AddFailed {
            get {
                return ResourceManager.GetString("Lib_AddFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library [{0}] removed..
        /// </summary>
        public static string Lib_Removed {
            get {
                return ResourceManager.GetString("Lib_Removed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This library is already in the list..
        /// </summary>
        public static string Lib_AlreadyAdded {
            get {
                return ResourceManager.GetString("Lib_AlreadyAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No libraries yet. Add a project folder, a network share or an evarsXXX.bat file above..
        /// </summary>
        public static string Lib_Empty {
            get {
                return ResourceManager.GetString("Lib_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network path did not respond within {0} s.
        /// </summary>
        public static string Scan_Timeout {
            get {
                return ResourceManager.GetString("Scan_Timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host is offline (no answer on SMB port 445).
        /// </summary>
        public static string Scan_HostOffline {
            get {
                return ResourceManager.GetString("Scan_HostOffline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path does not exist or is not accessible.
        /// </summary>
        public static string Scan_NotFound {
            get {
                return ResourceManager.GetString("Scan_NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access denied: {0}.
        /// </summary>
        public static string Scan_AccessDenied {
            get {
                return ResourceManager.GetString("Scan_AccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No evarsXXX.bat project files were found there.
        /// </summary>
        public static string Scan_NoProjects {
            get {
                return ResourceManager.GetString("Scan_NoProjects", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file is not an evarsXXX.bat or custom_evars.bat.
        /// </summary>
        public static string Scan_NotProjectFile {
            get {
                return ResourceManager.GetString("Scan_NotProjectFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL libraries are not supported yet.
        /// </summary>
        public static string Scan_Unsupported {
            get {
                return ResourceManager.GetString("Scan_Unsupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scan failed: {0}.
        /// </summary>
        public static string Scan_Error {
            get {
                return ResourceManager.GetString("Scan_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library [{0}] loaded: E3D now lists all of its projects..
        /// </summary>
        public static string Launch_Library {
            get {
                return ResourceManager.GetString("Launch_Library", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library path is not accessible: {0}.
        /// </summary>
        public static string Launch_LibraryUnreachable {
            get {
                return ResourceManager.GetString("Launch_LibraryUnreachable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project file is not accessible: {0}.
        /// </summary>
        public static string Launch_ProjectFileUnreachable {
            get {
                return ResourceManager.GetString("Launch_ProjectFileUnreachable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local project library for single-project launches (local_projects_dir).
        /// </summary>
        public static string Settings_LocalProjectsDirLabel {
            get {
                return ResourceManager.GetString("Settings_LocalProjectsDirLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E3D shortcut (.lnk) – optional, found automatically when empty.
        /// </summary>
        public static string Settings_LnkLabel {
            get {
                return ResourceManager.GetString("Settings_LnkLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No project code (XXX000=) could be read from this project's evars file..
        /// </summary>
        public static string Users_NoCode {
            get {
                return ResourceManager.GetString("Users_NoCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The project code must be 2–5 letters or digits (e.g. PRJ, APS, M01)..
        /// </summary>
        public static string Create_InvalidCode {
            get {
                return ResourceManager.GetString("Create_InvalidCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a project name or description..
        /// </summary>
        public static string Create_NameRequired {
            get {
                return ResourceManager.GetString("Create_NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] was created and registered with E3D..
        /// </summary>
        public static string Create_Success {
            get {
                return ResourceManager.GetString("Create_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creation failed: {0}.
        /// </summary>
        public static string Create_Failed {
            get {
                return ResourceManager.GetString("Create_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The project folder does not exist..
        /// </summary>
        public static string Decommission_DirMissing {
            get {
                return ResourceManager.GetString("Decommission_DirMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} active lock file(s) were found in the project; decommissioning was blocked for safety..
        /// </summary>
        public static string Decommission_LocksFound {
            get {
                return ResourceManager.GetString("Decommission_LocksFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] was decommissioned and archived..
        /// </summary>
        public static string Decommission_Success {
            get {
                return ResourceManager.GetString("Decommission_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decommissioning failed: {0}.
        /// </summary>
        public static string Decommission_Failed {
            get {
                return ResourceManager.GetString("Decommission_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project startup script not found: evars{0}.bat.
        /// </summary>
        public static string Launch_EvarsMissing {
            get {
                return ResourceManager.GetString("Launch_EvarsMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active project switched to [{0}]..
        /// </summary>
        public static string Launch_SwitchSuccess {
            get {
                return ResourceManager.GetString("Launch_SwitchSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to switch project environment: {0}.
        /// </summary>
        public static string Launch_SwitchFailed {
            get {
                return ResourceManager.GetString("Launch_SwitchFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D was launched via the desktop shortcut..
        /// </summary>
        public static string Launch_ViaShortcut {
            get {
                return ResourceManager.GetString("Launch_ViaShortcut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D was launched..
        /// </summary>
        public static string Launch_ViaMonExe {
            get {
                return ResourceManager.GetString("Launch_ViaMonExe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No AVEVA E3D executable or shortcut was found. Configure the install path in Settings..
        /// </summary>
        public static string Launch_NotFound {
            get {
                return ResourceManager.GetString("Launch_NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to launch E3D: {0}.
        /// </summary>
        public static string Launch_Failed {
            get {
                return ResourceManager.GetString("Launch_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local project repository (projects_dir) is not configured. Set it in Settings..
        /// </summary>
        public static string Launch_ProjectsDirMissing {
            get {
                return ResourceManager.GetString("Launch_ProjectsDirMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path contains characters that are not allowed in a batch file: {0}.
        /// </summary>
        public static string Launch_UnsafePath {
            get {
                return ResourceManager.GetString("Launch_UnsafePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No projects_dir= line was found in {0}..
        /// </summary>
        public static string Launch_ProjectsDirLineMissing {
            get {
                return ResourceManager.GetString("Launch_ProjectsDirLineMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D installation folder.
        /// </summary>
        public static string Diag_InstallDirTitle {
            get {
                return ResourceManager.GetString("Diag_InstallDirTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Core environment.
        /// </summary>
        public static string Diag_CategoryCore {
            get {
                return ResourceManager.GetString("Diag_CategoryCore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found: {0} ({1}).
        /// </summary>
        public static string Diag_InstallDirFound {
            get {
                return ResourceManager.GetString("Diag_InstallDirFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No valid E3D installation path was detected. Configure it in Settings..
        /// </summary>
        public static string Diag_InstallDirMissing {
            get {
                return ResourceManager.GetString("Diag_InstallDirMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Environment script (evars.bat).
        /// </summary>
        public static string Diag_EvarsTitle {
            get {
                return ResourceManager.GetString("Diag_EvarsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System integration.
        /// </summary>
        public static string Diag_CategoryIntegration {
            get {
                return ResourceManager.GetString("Diag_CategoryIntegration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valid: {0}.
        /// </summary>
        public static string Diag_EvarsFound {
            get {
                return ResourceManager.GetString("Diag_EvarsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global evars.bat not found; project injection may not work..
        /// </summary>
        public static string Diag_EvarsMissing {
            get {
                return ResourceManager.GetString("Diag_EvarsMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local project repository (projects_dir).
        /// </summary>
        public static string Diag_ProjectsDirTitle {
            get {
                return ResourceManager.GetString("Diag_ProjectsDirTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data repository.
        /// </summary>
        public static string Diag_CategoryStorage {
            get {
                return ResourceManager.GetString("Diag_CategoryStorage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder OK: {0} | managed custom_evars: {1}.
        /// </summary>
        public static string Diag_ProjectsDirFound {
            get {
                return ResourceManager.GetString("Diag_ProjectsDirFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to present.
        /// </summary>
        public static string Diag_CustomEvarsPresent {
            get {
                return ResourceManager.GetString("Diag_CustomEvarsPresent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to not initialised.
        /// </summary>
        public static string Diag_CustomEvarsPending {
            get {
                return ResourceManager.GetString("Diag_CustomEvarsPending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local project folder does not exist. Create it or point to a valid drive..
        /// </summary>
        public static string Diag_ProjectsDirMissing {
            get {
                return ResourceManager.GetString("Diag_ProjectsDirMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Native runtime (.NET 10 &amp; DirectWrite/Mica).
        /// </summary>
        public static string Diag_RuntimeTitle {
            get {
                return ResourceManager.GetString("Diag_RuntimeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GUI engine.
        /// </summary>
        public static string Diag_CategoryGui {
            get {
                return ResourceManager.GetString("Diag_CategoryGui", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running natively on Windows 11 with hardware acceleration..
        /// </summary>
        public static string Diag_RuntimeDetail {
            get {
                return ResourceManager.GetString("Diag_RuntimeDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active / stale database lock.
        /// </summary>
        public static string Lock_StatusActive {
            get {
                return ResourceManager.GetString("Lock_StatusActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stale lock.
        /// </summary>
        public static string Lock_StatusOrphan {
            get {
                return ResourceManager.GetString("Lock_StatusOrphan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The lock file was already removed..
        /// </summary>
        public static string Unlock_AlreadyCleared {
            get {
                return ResourceManager.GetString("Unlock_AlreadyCleared", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Force-unlocked: {0}.
        /// </summary>
        public static string Unlock_Success {
            get {
                return ResourceManager.GetString("Unlock_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to unlock: {0}.
        /// </summary>
        public static string Unlock_Failed {
            get {
                return ResourceManager.GetString("Unlock_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Health Check &amp; Lock Inspection.
        /// </summary>
        public static string Diag_PageTitle {
            get {
                return ResourceManager.GetString("Diag_PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🔄 Re-run check.
        /// </summary>
        public static string Diag_Rerun {
            get {
                return ResourceManager.GetString("Diag_Rerun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🛡️ Clear all stale locks.
        /// </summary>
        public static string Diag_UnlockAll {
            get {
                return ResourceManager.GetString("Diag_UnlockAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Core environment checks.
        /// </summary>
        public static string Diag_CoreMetrics {
            get {
                return ResourceManager.GetString("Diag_CoreMetrics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database lock files across projects (active session locks).
        /// </summary>
        public static string Diag_LocksHeader {
            get {
                return ResourceManager.GetString("Diag_LocksHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} lock(s) found.
        /// </summary>
        public static string Diag_LocksCountFormat {
            get {
                return ResourceManager.GetString("Diag_LocksCountFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🔓 Unlock.
        /// </summary>
        public static string Diag_UnlockButton {
            get {
                return ResourceManager.GetString("Diag_UnlockButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running environment check and lock scan....
        /// </summary>
        public static string Diag_Running {
            get {
                return ResourceManager.GetString("Diag_Running", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check complete: {0} active/stale database lock(s) found..
        /// </summary>
        public static string Diag_Complete {
            get {
                return ResourceManager.GetString("Diag_Complete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diagnostics failed: {0}.
        /// </summary>
        public static string Diag_Error {
            get {
                return ResourceManager.GetString("Diag_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There are no lock files to clear..
        /// </summary>
        public static string Diag_NoLocks {
            get {
                return ResourceManager.GetString("Diag_NoLocks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clearing all stale locks....
        /// </summary>
        public static string Diag_ClearingAll {
            get {
                return ResourceManager.GetString("Diag_ClearingAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clean-up complete: {0} unlocked, {1} failed..
        /// </summary>
        public static string Diag_ClearAllDone {
            get {
                return ResourceManager.GetString("Diag_ClearAllDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users &amp; Permissions.
        /// </summary>
        public static string Users_PageTitle {
            get {
                return ResourceManager.GetString("Users_PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        public static string Users_CurrentProject {
            get {
                return ResourceManager.GetString("Users_CurrentProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh user list.
        /// </summary>
        public static string Users_RefreshTooltip {
            get {
                return ResourceManager.GetString("Users_RefreshTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Teams:.
        /// </summary>
        public static string Users_TeamsLabel {
            get {
                return ResourceManager.GetString("Users_TeamsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User name (code).
        /// </summary>
        public static string Users_NewNameLabel {
            get {
                return ResourceManager.GetString("Users_NewNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. JOHN.
        /// </summary>
        public static string Users_NewNamePlaceholder {
            get {
                return ResourceManager.GetString("Users_NewNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initial team.
        /// </summary>
        public static string Users_NewTeamLabel {
            get {
                return ResourceManager.GetString("Users_NewTeamLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initial password (optional).
        /// </summary>
        public static string Users_NewPasswordLabel {
            get {
                return ResourceManager.GetString("Users_NewPasswordLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security level.
        /// </summary>
        public static string Users_NewSecurityLabel {
            get {
                return ResourceManager.GetString("Users_NewSecurityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description / notes.
        /// </summary>
        public static string Users_NewDescLabel {
            get {
                return ResourceManager.GetString("Users_NewDescLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. Piping lead.
        /// </summary>
        public static string Users_NewDescPlaceholder {
            get {
                return ResourceManager.GetString("Users_NewDescPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ➕ Create user.
        /// </summary>
        public static string Users_CreateButton {
            get {
                return ResourceManager.GetString("Users_CreateButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reading users and teams for [{0}]....
        /// </summary>
        public static string Users_Loading {
            get {
                return ResourceManager.GetString("Users_Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1} user(s) and {2} team(s) found..
        /// </summary>
        public static string Users_Loaded {
            get {
                return ResourceManager.GetString("Users_Loaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read failed: {0}.
        /// </summary>
        public static string Users_LoadFailed {
            get {
                return ResourceManager.GetString("Users_LoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding user [{1}] to [{0}]....
        /// </summary>
        public static string Users_Adding {
            get {
                return ResourceManager.GetString("Users_Adding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleting user [{0}]....
        /// </summary>
        public static string Users_Deleting {
            get {
                return ResourceManager.GetString("Users_Deleting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User [{0}] was created and assigned to team [{1}]..
        /// </summary>
        public static string Admin_UserCreated {
            get {
                return ResourceManager.GetString("Admin_UserCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User [{0}] was deleted..
        /// </summary>
        public static string Admin_UserDeleted {
            get {
                return ResourceManager.GetString("Admin_UserDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User [{0}] was added to team [{1}]..
        /// </summary>
        public static string Admin_UserAddedToTeam {
            get {
                return ResourceManager.GetString("Admin_UserAddedToTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter a value..
        /// </summary>
        public static string Common_ValueRequired {
            get {
                return ResourceManager.GetString("Common_ValueRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project users, security levels and team membership through AVEVA Administration..
        /// </summary>
        public static string Users_PageSubtitle {
            get {
                return ResourceManager.GetString("Users_PageSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Administrator login.
        /// </summary>
        public static string Users_CredHeader {
            get {
                return ResourceManager.GetString("Users_CredHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A FREE user of the project (usually SYSTEM) is needed to read and change users..
        /// </summary>
        public static string Users_CredHint {
            get {
                return ResourceManager.GetString("Users_CredHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change….
        /// </summary>
        public static string Users_CredChange {
            get {
                return ResourceManager.GetString("Users_CredChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} · saved.
        /// </summary>
        public static string Users_CredSaved {
            get {
                return ResourceManager.GetString("Users_CredSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} · default.
        /// </summary>
        public static string Users_CredDefault {
            get {
                return ResourceManager.GetString("Users_CredDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Administrator (FREE user).
        /// </summary>
        public static string Users_CredUserLabel {
            get {
                return ResourceManager.GetString("Users_CredUserLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Users_CredPasswordLabel {
            get {
                return ResourceManager.GetString("Users_CredPasswordLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Users_CredTest {
            get {
                return ResourceManager.GetString("Users_CredTest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save &amp; use.
        /// </summary>
        public static string Users_CredSave {
            get {
                return ResourceManager.GetString("Users_CredSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forget.
        /// </summary>
        public static string Users_CredForget {
            get {
                return ResourceManager.GetString("Users_CredForget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved only on this computer, encrypted for your Windows account (sep_admin_creds.json)..
        /// </summary>
        public static string Users_CredStorageNote {
            get {
                return ResourceManager.GetString("Users_CredStorageNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the administrator user name..
        /// </summary>
        public static string Users_CredUserRequired {
            get {
                return ResourceManager.GetString("Users_CredUserRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opening the project with these credentials….
        /// </summary>
        public static string Users_CredTesting {
            get {
                return ResourceManager.GetString("Users_CredTesting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credentials not verified.
        /// </summary>
        public static string Users_CredSaveAnywayTitle {
            get {
                return ResourceManager.GetString("Users_CredSaveAnywayTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}  Save them anyway?.
        /// </summary>
        public static string Users_CredSaveAnywayBody {
            get {
                return ResourceManager.GetString("Users_CredSaveAnywayBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save anyway.
        /// </summary>
        public static string Users_CredSaveAnyway {
            get {
                return ResourceManager.GetString("Users_CredSaveAnyway", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not save credentials: {0}.
        /// </summary>
        public static string Users_CredSaveFailed {
            get {
                return ResourceManager.GetString("Users_CredSaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Administrator [{0}] saved for project [{1}]..
        /// </summary>
        public static string Users_CredSavedMsg {
            get {
                return ResourceManager.GetString("Users_CredSavedMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved credentials for [{0}] removed; SYSTEM/XXXXXX will be used..
        /// </summary>
        public static string Users_CredForgotten {
            get {
                return ResourceManager.GetString("Users_CredForgotten", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0}] showing the list from {1}; asking ADMIN for the current one….
        /// </summary>
        public static string Users_CachedShown {
            get {
                return ResourceManager.GetString("Users_CachedShown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1} user(s) and {2} team(s), listed {3}. Refresh to ask ADMIN again..
        /// </summary>
        public static string Users_CachedFresh {
            get {
                return ResourceManager.GetString("Users_CachedFresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to cached {0}.
        /// </summary>
        public static string Users_ListedCached {
            get {
                return ResourceManager.GetString("Users_ListedCached", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ADMIN {0}.
        /// </summary>
        public static string Users_ListedLive {
            get {
                return ResourceManager.GetString("Users_ListedLive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users_TabUsers {
            get {
                return ResourceManager.GetString("Users_TabUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Users_TabTeams {
            get {
                return ResourceManager.GetString("Users_TabTeams", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter users….
        /// </summary>
        public static string Users_FilterPlaceholder {
            get {
                return ResourceManager.GetString("Users_FilterPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter teams….
        /// </summary>
        public static string Users_FilterTeamsPlaceholder {
            get {
                return ResourceManager.GetString("Users_FilterTeamsPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string Users_NewUserButton {
            get {
                return ResourceManager.GetString("Users_NewUserButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New team.
        /// </summary>
        public static string Users_NewTeamButton {
            get {
                return ResourceManager.GetString("Users_NewTeamButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SYSTEM.
        /// </summary>
        public static string Users_SystemBadge {
            get {
                return ResourceManager.GetString("Users_SystemBadge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MASTER.
        /// </summary>
        public static string Users_MasterBadge {
            get {
                return ResourceManager.GetString("Users_MasterBadge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Users_SecurityGeneral {
            get {
                return ResourceManager.GetString("Users_SecurityGeneral", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Users_SecurityFree {
            get {
                return ResourceManager.GetString("Users_SecurityFree", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FREE users administer the project: they bypass access control and can open ADMIN..
        /// </summary>
        public static string Users_SecurityFreeHint {
            get {
                return ResourceManager.GetString("Users_SecurityFreeHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GENERAL users work in the design modules under the team/ACR rules..
        /// </summary>
        public static string Users_SecurityGeneralHint {
            get {
                return ResourceManager.GetString("Users_SecurityGeneralHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to no team.
        /// </summary>
        public static string Users_NoTeams {
            get {
                return ResourceManager.GetString("Users_NoTeams", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to no members.
        /// </summary>
        public static string Users_NoMembers {
            get {
                return ResourceManager.GetString("Users_NoMembers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Members:.
        /// </summary>
        public static string Users_MembersLabel {
            get {
                return ResourceManager.GetString("Users_MembersLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} member(s).
        /// </summary>
        public static string Users_MemberCount {
            get {
                return ResourceManager.GetString("Users_MemberCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add to a team.
        /// </summary>
        public static string Users_AddToTeamTooltip {
            get {
                return ResourceManager.GetString("Users_AddToTeamTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a member.
        /// </summary>
        public static string Users_AddMemberTooltip {
            get {
                return ResourceManager.GetString("Users_AddMemberTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove from this team.
        /// </summary>
        public static string Users_RemoveMemberTooltip {
            get {
                return ResourceManager.GetString("Users_RemoveMemberTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string Users_PasswordTooltip {
            get {
                return ResourceManager.GetString("Users_PasswordTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change security level (Free ⇄ General).
        /// </summary>
        public static string Users_SecurityTooltip {
            get {
                return ResourceManager.GetString("Users_SecurityTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit description.
        /// </summary>
        public static string Users_DescriptionTooltip {
            get {
                return ResourceManager.GetString("Users_DescriptionTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string Users_DeleteTooltip {
            get {
                return ResourceManager.GetString("Users_DeleteTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete team.
        /// </summary>
        public static string Users_DeleteTeamTooltip {
            get {
                return ResourceManager.GetString("Users_DeleteTeamTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string Users_DeleteTitle {
            get {
                return ResourceManager.GetString("Users_DeleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete user {0} from project {1}? This cannot be undone..
        /// </summary>
        public static string Users_DeleteBody {
            get {
                return ResourceManager.GetString("Users_DeleteBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Users_DeleteConfirm {
            get {
                return ResourceManager.GetString("Users_DeleteConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set password for {0}.
        /// </summary>
        public static string Users_PasswordTitle {
            get {
                return ResourceManager.GetString("Users_PasswordTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The new password takes effect immediately for {0} in project {1}..
        /// </summary>
        public static string Users_PasswordBody {
            get {
                return ResourceManager.GetString("Users_PasswordBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Users_PasswordLabel {
            get {
                return ResourceManager.GetString("Users_PasswordLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string Users_PasswordRepeatLabel {
            get {
                return ResourceManager.GetString("Users_PasswordRepeatLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Up to 32 characters; no spaces, quotes or the | character..
        /// </summary>
        public static string Users_PasswordRules {
            get {
                return ResourceManager.GetString("Users_PasswordRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the new password..
        /// </summary>
        public static string Users_PasswordEmpty {
            get {
                return ResourceManager.GetString("Users_PasswordEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The two passwords do not match..
        /// </summary>
        public static string Users_PasswordMismatch {
            get {
                return ResourceManager.GetString("Users_PasswordMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string Users_PasswordConfirm {
            get {
                return ResourceManager.GetString("Users_PasswordConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Changing the password of [{0}]….
        /// </summary>
        public static string Users_ChangingPassword {
            get {
                return ResourceManager.GetString("Users_ChangingPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change security level.
        /// </summary>
        public static string Users_SecurityTitle {
            get {
                return ResourceManager.GetString("Users_SecurityTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make {0} a GENERAL user? It will no longer be able to administer the project..
        /// </summary>
        public static string Users_SecurityToGeneralBody {
            get {
                return ResourceManager.GetString("Users_SecurityToGeneralBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make {0} a FREE user? FREE users bypass all access control and can open ADMIN..
        /// </summary>
        public static string Users_SecurityToFreeBody {
            get {
                return ResourceManager.GetString("Users_SecurityToFreeBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make {0}.
        /// </summary>
        public static string Users_SecurityConfirm {
            get {
                return ResourceManager.GetString("Users_SecurityConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Changing the security level of [{0}]….
        /// </summary>
        public static string Users_ChangingSecurity {
            get {
                return ResourceManager.GetString("Users_ChangingSecurity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description of {0}.
        /// </summary>
        public static string Users_DescriptionTitle {
            get {
                return ResourceManager.GetString("Users_DescriptionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating the description of [{0}]….
        /// </summary>
        public static string Users_UpdatingDescription {
            get {
                return ResourceManager.GetString("Users_UpdatingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add {0} to a team.
        /// </summary>
        public static string Users_AddToTeamTitle {
            get {
                return ResourceManager.GetString("Users_AddToTeamTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Users_TeamLabel {
            get {
                return ResourceManager.GetString("Users_TeamLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Users_UserLabel {
            get {
                return ResourceManager.GetString("Users_UserLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Team name.
        /// </summary>
        public static string Users_TeamNameLabel {
            get {
                return ResourceManager.GetString("Users_TeamNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. PIPING.
        /// </summary>
        public static string Users_TeamNamePlaceholder {
            get {
                return ResourceManager.GetString("Users_TeamNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Users_AddToTeamConfirm {
            get {
                return ResourceManager.GetString("Users_AddToTeamConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding [{0}] to team [{1}]….
        /// </summary>
        public static string Users_AddingToTeam {
            get {
                return ResourceManager.GetString("Users_AddingToTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove from team.
        /// </summary>
        public static string Users_RemoveMemberTitle {
            get {
                return ResourceManager.GetString("Users_RemoveMemberTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove {0} from team {1}?.
        /// </summary>
        public static string Users_RemoveMemberBody {
            get {
                return ResourceManager.GetString("Users_RemoveMemberBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Users_RemoveMemberConfirm {
            get {
                return ResourceManager.GetString("Users_RemoveMemberConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removing [{0}] from team [{1}]….
        /// </summary>
        public static string Users_RemovingMember {
            get {
                return ResourceManager.GetString("Users_RemovingMember", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New team in {0}.
        /// </summary>
        public static string Users_NewTeamTitle {
            get {
                return ResourceManager.GetString("Users_NewTeamTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create team.
        /// </summary>
        public static string Users_NewTeamConfirm {
            get {
                return ResourceManager.GetString("Users_NewTeamConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating team [{0}]….
        /// </summary>
        public static string Users_CreatingTeam {
            get {
                return ResourceManager.GetString("Users_CreatingTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete team.
        /// </summary>
        public static string Users_DeleteTeamTitle {
            get {
                return ResourceManager.GetString("Users_DeleteTeamTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete team {0} ({1} member(s))? Databases owned by the team keep ADMIN from deleting it..
        /// </summary>
        public static string Users_DeleteTeamBody {
            get {
                return ResourceManager.GetString("Users_DeleteTeamBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete team.
        /// </summary>
        public static string Users_DeleteTeamConfirm {
            get {
                return ResourceManager.GetString("Users_DeleteTeamConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleting team [{0}]….
        /// </summary>
        public static string Users_DeletingTeam {
            get {
                return ResourceManager.GetString("Users_DeletingTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a member to {0}.
        /// </summary>
        public static string Users_AddMemberTitle {
            get {
                return ResourceManager.GetString("Users_AddMemberTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add member.
        /// </summary>
        public static string Users_AddMemberConfirm {
            get {
                return ResourceManager.GetString("Users_AddMemberConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user is created through AVEVA Administration and can log into E3D right away..
        /// </summary>
        public static string Users_NewIntro {
            get {
                return ResourceManager.GetString("Users_NewIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New user in {0}.
        /// </summary>
        public static string Users_NewTitle {
            get {
                return ResourceManager.GetString("Users_NewTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (no team).
        /// </summary>
        public static string Users_NoTeamOption {
            get {
                return ResourceManager.GetString("Users_NoTeamOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User names are 1–32 letters, digits or underscores..
        /// </summary>
        public static string Users_NameInvalid {
            get {
                return ResourceManager.GetString("Users_NameInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Team names are 1–32 letters, digits or underscores..
        /// </summary>
        public static string Users_TeamNameInvalid {
            get {
                return ResourceManager.GetString("Users_TeamNameInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0}] can administer project [{1}]..
        /// </summary>
        public static string Admin_VerifyOk {
            get {
                return ResourceManager.GetString("Admin_VerifyOk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User [{0}] was created..
        /// </summary>
        public static string Admin_UserCreatedNoTeam {
            get {
                return ResourceManager.GetString("Admin_UserCreatedNoTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password of [{0}] changed..
        /// </summary>
        public static string Admin_PasswordChanged {
            get {
                return ResourceManager.GetString("Admin_PasswordChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0}] is now a {1} user..
        /// </summary>
        public static string Admin_SecurityChanged {
            get {
                return ResourceManager.GetString("Admin_SecurityChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description of [{0}] updated..
        /// </summary>
        public static string Admin_DescriptionChanged {
            get {
                return ResourceManager.GetString("Admin_DescriptionChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User [{0}] was removed from team [{1}]..
        /// </summary>
        public static string Admin_UserRemovedFromTeam {
            get {
                return ResourceManager.GetString("Admin_UserRemovedFromTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Team [{0}] was created..
        /// </summary>
        public static string Admin_TeamCreated {
            get {
                return ResourceManager.GetString("Admin_TeamCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Team [{0}] was deleted..
        /// </summary>
        public static string Admin_TeamDeleted {
            get {
                return ResourceManager.GetString("Admin_TeamDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not open project [{0}]: the administrator login is wrong or the project databases are not reachable. Check the administrator login above..
        /// </summary>
        public static string Admin_ErrConnect {
            get {
                return ResourceManager.GetString("Admin_ErrConnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] is read-only for this administrator..
        /// </summary>
        public static string Admin_ErrReadOnly {
            get {
                return ResourceManager.GetString("Admin_ErrReadOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA Administration did not answer in time (is a licence available?)..
        /// </summary>
        public static string Admin_ErrTimeout {
            get {
                return ResourceManager.GetString("Admin_ErrTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA Administration was not found: {0}.
        /// </summary>
        public static string Admin_ErrExeMissing {
            get {
                return ResourceManager.GetString("Admin_ErrExeMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D core paths.
        /// </summary>
        public static string Settings_PathsHeader {
            get {
                return ResourceManager.GetString("Settings_PathsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E3D installation folder (install_dir).
        /// </summary>
        public static string Settings_InstallDirLabel {
            get {
                return ResourceManager.GetString("Settings_InstallDirLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. D:\AVEVA\Everything3D3.1.
        /// </summary>
        public static string Settings_InstallDirPlaceholder {
            get {
                return ResourceManager.GetString("Settings_InstallDirPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local project repository (projects_dir).
        /// </summary>
        public static string Settings_ProjectsDirLabel {
            get {
                return ResourceManager.GetString("Settings_ProjectsDirLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. D:\AVEVA\Projects\E3D3.1.
        /// </summary>
        public static string Settings_ProjectsDirPlaceholder {
            get {
                return ResourceManager.GetString("Settings_ProjectsDirPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global environment script (evars.bat).
        /// </summary>
        public static string Settings_EvarsLabel {
            get {
                return ResourceManager.GetString("Settings_EvarsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. D:\AVEVA\Everything3D3.1\evars.bat.
        /// </summary>
        public static string Settings_EvarsPlaceholder {
            get {
                return ResourceManager.GetString("Settings_EvarsPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E3D version label.
        /// </summary>
        public static string Settings_VersionLabel {
            get {
                return ResourceManager.GetString("Settings_VersionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. AVEVA Everything3D 3.1.
        /// </summary>
        public static string Settings_VersionPlaceholder {
            get {
                return ResourceManager.GetString("Settings_VersionPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client preferences.
        /// </summary>
        public static string Settings_PreferencesHeader {
            get {
                return ResourceManager.GetString("Settings_PreferencesHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start with Windows (keep the environment ready).
        /// </summary>
        public static string Settings_AutoStart {
            get {
                return ResourceManager.GetString("Settings_AutoStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_LanguageLabel {
            get {
                return ResourceManager.GetString("Settings_LanguageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto (follow Windows).
        /// </summary>
        public static string Settings_LanguageAuto {
            get {
                return ResourceManager.GetString("Settings_LanguageAuto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About SEP.
        /// </summary>
        public static string Settings_AboutHeader {
            get {
                return ResourceManager.GetString("Settings_AboutHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SEP · AVEVA E3D Smart Project Manager.
        /// </summary>
        public static string Settings_AboutTagline {
            get {
                return ResourceManager.GetString("Settings_AboutTagline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Architecture: C# .NET 10 (DirectWrite / Windows 11 Mica).
        /// </summary>
        public static string Settings_AboutArch {
            get {
                return ResourceManager.GetString("Settings_AboutArch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Design: professional &amp; minimal (Obsidian Deep &amp; Fluent 2.0).
        /// </summary>
        public static string Settings_AboutStyle {
            get {
                return ResourceManager.GetString("Settings_AboutStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 💾 Save &amp; apply settings.
        /// </summary>
        public static string Settings_SaveButton {
            get {
                return ResourceManager.GetString("Settings_SaveButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        public static string Settings_Saved {
            get {
                return ResourceManager.GetString("Settings_Saved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D – New standardised project.
        /// </summary>
        public static string Create_Header {
            get {
                return ResourceManager.GetString("Create_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code (2–5 chars).
        /// </summary>
        public static string Create_CodeLabel {
            get {
                return ResourceManager.GetString("Create_CodeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. PRJ.
        /// </summary>
        public static string Create_CodePlaceholder {
            get {
                return ResourceManager.GetString("Create_CodePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project name / description.
        /// </summary>
        public static string Create_NameLabel {
            get {
                return ResourceManager.GetString("Create_NameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. 200 kt/a ethylene plant.
        /// </summary>
        public static string Create_NamePlaceholder {
            get {
                return ResourceManager.GetString("Create_NamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project root folder.
        /// </summary>
        public static string Create_RootDirLabel {
            get {
                return ResourceManager.GetString("Create_RootDirLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clone configuration from an existing project.
        /// </summary>
        public static string Create_CloneCheckbox {
            get {
                return ResourceManager.GetString("Create_CloneCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 💡 The 000/ISO/DWG/MAC/PIC/DFLTS folder skeleton and evars.bat are generated automatically, and the project is registered in ProjectInfo.xml and projects.ini..
        /// </summary>
        public static string Create_Hint {
            get {
                return ResourceManager.GetString("Create_Hint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✨ Create project.
        /// </summary>
        public static string Create_Button {
            get {
                return ResourceManager.GetString("Create_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decommission &amp; Archive.
        /// </summary>
        public static string Decommission_Title {
            get {
                return ResourceManager.GetString("Decommission_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D – Decommission &amp; cold archive.
        /// </summary>
        public static string Decommission_Header {
            get {
                return ResourceManager.GetString("Decommission_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Archive the project as a ZIP file (cold backup).
        /// </summary>
        public static string Decommission_ArchiveCheckbox {
            get {
                return ResourceManager.GetString("Decommission_ArchiveCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unregister from ProjectInfo.xml and projects.ini.
        /// </summary>
        public static string Decommission_UnregisterCheckbox {
            get {
                return ResourceManager.GetString("Decommission_UnregisterCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete the project folder from disk (dangerous).
        /// </summary>
        public static string Decommission_DeleteCheckbox {
            get {
                return ResourceManager.GetString("Decommission_DeleteCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Archive folder:.
        /// </summary>
        public static string Decommission_ArchiveDirLabel {
            get {
                return ResourceManager.GetString("Decommission_ArchiveDirLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 📦 Confirm decommission.
        /// </summary>
        public static string Decommission_Button {
            get {
                return ResourceManager.GetString("Decommission_Button", resourceCulture);
            }
        }
    }
}
