//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP.App.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SEP.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SEP startup error.
        /// </summary>
        public static string App_FatalTitle {
            get {
                return ResourceManager.GetString("App_FatalTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [SEP fatal startup error] {0}  Details were written to sep_debug.log.
        /// </summary>
        public static string App_FatalBody {
            get {
                return ResourceManager.GetString("App_FatalBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SEP error.
        /// </summary>
        public static string App_UiErrorTitle {
            get {
                return ResourceManager.GetString("App_UiErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [SEP UI exception] {0}  Details were written to sep_debug.log.
        /// </summary>
        public static string App_UiErrorBody {
            get {
                return ResourceManager.GetString("App_UiErrorBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Startup failed: {0} {1}.
        /// </summary>
        public static string App_StartupFailed {
            get {
                return ResourceManager.GetString("App_StartupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Common_Ready {
            get {
                return ResourceManager.GetString("Common_Ready", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SEP · AVEVA E3D Project Manager.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active project: .
        /// </summary>
        public static string Main_ActiveProjectLabel {
            get {
                return ResourceManager.GetString("Main_ActiveProjectLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🚀 Launch E3D now.
        /// </summary>
        public static string Main_LaunchButton {
            get {
                return ResourceManager.GetString("Main_LaunchButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch to the active project and launch E3D.
        /// </summary>
        public static string Main_LaunchTooltip {
            get {
                return ResourceManager.GetString("Main_LaunchTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project Workbench.
        /// </summary>
        public static string Nav_Projects {
            get {
                return ResourceManager.GetString("Nav_Projects", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users &amp; Permissions.
        /// </summary>
        public static string Nav_UserAdmin {
            get {
                return ResourceManager.GetString("Nav_UserAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Health Check.
        /// </summary>
        public static string Nav_Diagnostics {
            get {
                return ResourceManager.GetString("Nav_Diagnostics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System &amp; Path Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No active project.
        /// </summary>
        public static string Main_NoActiveProject {
            get {
                return ResourceManager.GetString("Main_NoActiveProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No active project selected.
        /// </summary>
        public static string Main_NoActiveProjectSet {
            get {
                return ResourceManager.GetString("Main_NoActiveProjectSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not selected.
        /// </summary>
        public static string Main_StatusPending {
            get {
                return ResourceManager.GetString("Main_StatusPending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a project in the Project Workbench first..
        /// </summary>
        public static string Main_SelectProjectFirst {
            get {
                return ResourceManager.GetString("Main_SelectProjectFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No path is configured for active project [{0}]..
        /// </summary>
        public static string Main_ActiveProjectPathMissing {
            get {
                return ResourceManager.GetString("Main_ActiveProjectPathMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switching environment and launching AVEVA E3D [{0}]....
        /// </summary>
        public static string Main_SwitchingAndLaunching {
            get {
                return ResourceManager.GetString("Main_SwitchingAndLaunching", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Projects_FilterAll {
            get {
                return ResourceManager.GetString("Projects_FilterAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ★ Favorites.
        /// </summary>
        public static string Projects_FilterFavorites {
            get {
                return ResourceManager.GetString("Projects_FilterFavorites", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 💻 Local.
        /// </summary>
        public static string Projects_FilterLocal {
            get {
                return ResourceManager.GetString("Projects_FilterLocal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🌐 Network.
        /// </summary>
        public static string Projects_FilterUnc {
            get {
                return ResourceManager.GetString("Projects_FilterUnc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search code or path....
        /// </summary>
        public static string Projects_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Projects_SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✨ New project.
        /// </summary>
        public static string Projects_CreateButton {
            get {
                return ResourceManager.GetString("Projects_CreateButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh project list.
        /// </summary>
        public static string Projects_RefreshTooltip {
            get {
                return ResourceManager.GetString("Projects_RefreshTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string Projects_OpenFolderTooltip {
            get {
                return ResourceManager.GetString("Projects_OpenFolderTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ● Active project.
        /// </summary>
        public static string Projects_ActiveBadge {
            get {
                return ResourceManager.GetString("Projects_ActiveBadge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🚀 Switch &amp; launch E3D.
        /// </summary>
        public static string Projects_SwitchAndLaunch {
            get {
                return ResourceManager.GetString("Projects_SwitchAndLaunch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decommission &amp; manage.
        /// </summary>
        public static string Projects_MoreTooltip {
            get {
                return ResourceManager.GetString("Projects_MoreTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanning E3D projects and lock status....
        /// </summary>
        public static string Projects_Scanning {
            get {
                return ResourceManager.GetString("Projects_Scanning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} E3D project(s).
        /// </summary>
        public static string Projects_Loaded {
            get {
                return ResourceManager.GetString("Projects_Loaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project scan failed: {0}.
        /// </summary>
        public static string Projects_ScanError {
            get {
                return ResourceManager.GetString("Projects_ScanError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switching active project to [{0}] and launching E3D....
        /// </summary>
        public static string Projects_SwitchingTo {
            get {
                return ResourceManager.GetString("Projects_SwitchingTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ⚠ Active database lock.
        /// </summary>
        public static string Project_LockActive {
            get {
                return ResourceManager.GetString("Project_LockActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✓ No locks.
        /// </summary>
        public static string Project_LockFree {
            get {
                return ResourceManager.GetString("Project_LockFree", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Project_SourceLocal {
            get {
                return ResourceManager.GetString("Project_SourceLocal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network (UNC).
        /// </summary>
        public static string Project_SourceUnc {
            get {
                return ResourceManager.GetString("Project_SourceUnc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host offline.
        /// </summary>
        public static string Project_HostOffline {
            get {
                return ResourceManager.GetString("Project_HostOffline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not mounted / offline.
        /// </summary>
        public static string Project_NotMounted {
            get {
                return ResourceManager.GetString("Project_NotMounted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Project_DefaultCategory {
            get {
                return ResourceManager.GetString("Project_DefaultCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The project code must be 2–5 letters or digits (e.g. PRJ, APS, M01)..
        /// </summary>
        public static string Create_InvalidCode {
            get {
                return ResourceManager.GetString("Create_InvalidCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a project name or description..
        /// </summary>
        public static string Create_NameRequired {
            get {
                return ResourceManager.GetString("Create_NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] was created and registered with E3D..
        /// </summary>
        public static string Create_Success {
            get {
                return ResourceManager.GetString("Create_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creation failed: {0}.
        /// </summary>
        public static string Create_Failed {
            get {
                return ResourceManager.GetString("Create_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The project folder does not exist..
        /// </summary>
        public static string Decommission_DirMissing {
            get {
                return ResourceManager.GetString("Decommission_DirMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} active lock file(s) were found in the project; decommissioning was blocked for safety..
        /// </summary>
        public static string Decommission_LocksFound {
            get {
                return ResourceManager.GetString("Decommission_LocksFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project [{0}] was decommissioned and archived..
        /// </summary>
        public static string Decommission_Success {
            get {
                return ResourceManager.GetString("Decommission_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decommissioning failed: {0}.
        /// </summary>
        public static string Decommission_Failed {
            get {
                return ResourceManager.GetString("Decommission_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project startup script not found: evars{0}.bat.
        /// </summary>
        public static string Launch_EvarsMissing {
            get {
                return ResourceManager.GetString("Launch_EvarsMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active project switched to [{0}]..
        /// </summary>
        public static string Launch_SwitchSuccess {
            get {
                return ResourceManager.GetString("Launch_SwitchSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to switch project environment: {0}.
        /// </summary>
        public static string Launch_SwitchFailed {
            get {
                return ResourceManager.GetString("Launch_SwitchFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D was launched via the desktop shortcut..
        /// </summary>
        public static string Launch_ViaShortcut {
            get {
                return ResourceManager.GetString("Launch_ViaShortcut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D was launched..
        /// </summary>
        public static string Launch_ViaMonExe {
            get {
                return ResourceManager.GetString("Launch_ViaMonExe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No AVEVA E3D executable or shortcut was found. Configure the install path in Settings..
        /// </summary>
        public static string Launch_NotFound {
            get {
                return ResourceManager.GetString("Launch_NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to launch E3D: {0}.
        /// </summary>
        public static string Launch_Failed {
            get {
                return ResourceManager.GetString("Launch_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D installation folder.
        /// </summary>
        public static string Diag_InstallDirTitle {
            get {
                return ResourceManager.GetString("Diag_InstallDirTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Core environment.
        /// </summary>
        public static string Diag_CategoryCore {
            get {
                return ResourceManager.GetString("Diag_CategoryCore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found: {0} ({1}).
        /// </summary>
        public static string Diag_InstallDirFound {
            get {
                return ResourceManager.GetString("Diag_InstallDirFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No valid E3D installation path was detected. Configure it in Settings..
        /// </summary>
        public static string Diag_InstallDirMissing {
            get {
                return ResourceManager.GetString("Diag_InstallDirMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Environment script (evars.bat).
        /// </summary>
        public static string Diag_EvarsTitle {
            get {
                return ResourceManager.GetString("Diag_EvarsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System integration.
        /// </summary>
        public static string Diag_CategoryIntegration {
            get {
                return ResourceManager.GetString("Diag_CategoryIntegration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valid: {0}.
        /// </summary>
        public static string Diag_EvarsFound {
            get {
                return ResourceManager.GetString("Diag_EvarsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global evars.bat not found; project injection may not work..
        /// </summary>
        public static string Diag_EvarsMissing {
            get {
                return ResourceManager.GetString("Diag_EvarsMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local project repository (projects_dir).
        /// </summary>
        public static string Diag_ProjectsDirTitle {
            get {
                return ResourceManager.GetString("Diag_ProjectsDirTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data repository.
        /// </summary>
        public static string Diag_CategoryStorage {
            get {
                return ResourceManager.GetString("Diag_CategoryStorage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder OK: {0} | managed custom_evars: {1}.
        /// </summary>
        public static string Diag_ProjectsDirFound {
            get {
                return ResourceManager.GetString("Diag_ProjectsDirFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to present.
        /// </summary>
        public static string Diag_CustomEvarsPresent {
            get {
                return ResourceManager.GetString("Diag_CustomEvarsPresent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to not initialised.
        /// </summary>
        public static string Diag_CustomEvarsPending {
            get {
                return ResourceManager.GetString("Diag_CustomEvarsPending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local project folder does not exist. Create it or point to a valid drive..
        /// </summary>
        public static string Diag_ProjectsDirMissing {
            get {
                return ResourceManager.GetString("Diag_ProjectsDirMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Native runtime (.NET 10 &amp; DirectWrite/Mica).
        /// </summary>
        public static string Diag_RuntimeTitle {
            get {
                return ResourceManager.GetString("Diag_RuntimeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GUI engine.
        /// </summary>
        public static string Diag_CategoryGui {
            get {
                return ResourceManager.GetString("Diag_CategoryGui", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running natively on Windows 11 with hardware acceleration..
        /// </summary>
        public static string Diag_RuntimeDetail {
            get {
                return ResourceManager.GetString("Diag_RuntimeDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active / stale database lock.
        /// </summary>
        public static string Lock_StatusActive {
            get {
                return ResourceManager.GetString("Lock_StatusActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stale lock.
        /// </summary>
        public static string Lock_StatusOrphan {
            get {
                return ResourceManager.GetString("Lock_StatusOrphan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The lock file was already removed..
        /// </summary>
        public static string Unlock_AlreadyCleared {
            get {
                return ResourceManager.GetString("Unlock_AlreadyCleared", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Force-unlocked: {0}.
        /// </summary>
        public static string Unlock_Success {
            get {
                return ResourceManager.GetString("Unlock_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to unlock: {0}.
        /// </summary>
        public static string Unlock_Failed {
            get {
                return ResourceManager.GetString("Unlock_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Health Check &amp; Lock Inspection.
        /// </summary>
        public static string Diag_PageTitle {
            get {
                return ResourceManager.GetString("Diag_PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🔄 Re-run check.
        /// </summary>
        public static string Diag_Rerun {
            get {
                return ResourceManager.GetString("Diag_Rerun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🛡️ Clear all stale locks.
        /// </summary>
        public static string Diag_UnlockAll {
            get {
                return ResourceManager.GetString("Diag_UnlockAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Core environment checks.
        /// </summary>
        public static string Diag_CoreMetrics {
            get {
                return ResourceManager.GetString("Diag_CoreMetrics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database lock files across projects (active session locks).
        /// </summary>
        public static string Diag_LocksHeader {
            get {
                return ResourceManager.GetString("Diag_LocksHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} lock(s) found.
        /// </summary>
        public static string Diag_LocksCountFormat {
            get {
                return ResourceManager.GetString("Diag_LocksCountFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🔓 Unlock.
        /// </summary>
        public static string Diag_UnlockButton {
            get {
                return ResourceManager.GetString("Diag_UnlockButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running environment check and lock scan....
        /// </summary>
        public static string Diag_Running {
            get {
                return ResourceManager.GetString("Diag_Running", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check complete: {0} active/stale database lock(s) found..
        /// </summary>
        public static string Diag_Complete {
            get {
                return ResourceManager.GetString("Diag_Complete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diagnostics failed: {0}.
        /// </summary>
        public static string Diag_Error {
            get {
                return ResourceManager.GetString("Diag_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There are no lock files to clear..
        /// </summary>
        public static string Diag_NoLocks {
            get {
                return ResourceManager.GetString("Diag_NoLocks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clearing all stale locks....
        /// </summary>
        public static string Diag_ClearingAll {
            get {
                return ResourceManager.GetString("Diag_ClearingAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clean-up complete: {0} unlocked, {1} failed..
        /// </summary>
        public static string Diag_ClearAllDone {
            get {
                return ResourceManager.GetString("Diag_ClearAllDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users &amp; Permissions.
        /// </summary>
        public static string Users_PageTitle {
            get {
                return ResourceManager.GetString("Users_PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        public static string Users_CurrentProject {
            get {
                return ResourceManager.GetString("Users_CurrentProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh user list.
        /// </summary>
        public static string Users_RefreshTooltip {
            get {
                return ResourceManager.GetString("Users_RefreshTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project users.
        /// </summary>
        public static string Users_ListHeader {
            get {
                return ResourceManager.GetString("Users_ListHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} user(s).
        /// </summary>
        public static string Users_CountFormat {
            get {
                return ResourceManager.GetString("Users_CountFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Teams: {0}.
        /// </summary>
        public static string Users_TeamsFormat {
            get {
                return ResourceManager.GetString("Users_TeamsFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected user.
        /// </summary>
        public static string Users_SelectedHeader {
            get {
                return ResourceManager.GetString("Users_SelectedHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User code:.
        /// </summary>
        public static string Users_NameLabel {
            get {
                return ResourceManager.GetString("Users_NameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security level:.
        /// </summary>
        public static string Users_SecurityLabel {
            get {
                return ResourceManager.GetString("Users_SecurityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Teams:.
        /// </summary>
        public static string Users_TeamsLabel {
            get {
                return ResourceManager.GetString("Users_TeamsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Delete this user.
        /// </summary>
        public static string Users_DeleteButton {
            get {
                return ResourceManager.GetString("Users_DeleteButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New project user.
        /// </summary>
        public static string Users_NewHeader {
            get {
                return ResourceManager.GetString("Users_NewHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User name (code).
        /// </summary>
        public static string Users_NewNameLabel {
            get {
                return ResourceManager.GetString("Users_NewNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. JOHN.
        /// </summary>
        public static string Users_NewNamePlaceholder {
            get {
                return ResourceManager.GetString("Users_NewNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initial team.
        /// </summary>
        public static string Users_NewTeamLabel {
            get {
                return ResourceManager.GetString("Users_NewTeamLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. *MASTER or *PIPING.
        /// </summary>
        public static string Users_NewTeamPlaceholder {
            get {
                return ResourceManager.GetString("Users_NewTeamPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initial password (optional, blank by default).
        /// </summary>
        public static string Users_NewPasswordLabel {
            get {
                return ResourceManager.GetString("Users_NewPasswordLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security level.
        /// </summary>
        public static string Users_NewSecurityLabel {
            get {
                return ResourceManager.GetString("Users_NewSecurityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description / notes.
        /// </summary>
        public static string Users_NewDescLabel {
            get {
                return ResourceManager.GetString("Users_NewDescLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. Piping lead.
        /// </summary>
        public static string Users_NewDescPlaceholder {
            get {
                return ResourceManager.GetString("Users_NewDescPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ➕ Create user.
        /// </summary>
        public static string Users_CreateButton {
            get {
                return ResourceManager.GetString("Users_CreateButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reading users and teams for [{0}]....
        /// </summary>
        public static string Users_Loading {
            get {
                return ResourceManager.GetString("Users_Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1} user(s) and {2} team(s) found..
        /// </summary>
        public static string Users_Loaded {
            get {
                return ResourceManager.GetString("Users_Loaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read failed: {0}.
        /// </summary>
        public static string Users_LoadFailed {
            get {
                return ResourceManager.GetString("Users_LoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a user name and an initial team..
        /// </summary>
        public static string Users_InputRequired {
            get {
                return ResourceManager.GetString("Users_InputRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding user [{1}] to [{0}]....
        /// </summary>
        public static string Users_Adding {
            get {
                return ResourceManager.GetString("Users_Adding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleting user [{0}]....
        /// </summary>
        public static string Users_Deleting {
            get {
                return ResourceManager.GetString("Users_Deleting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User [{0}] was created and assigned to team [{1}]..
        /// </summary>
        public static string Admin_UserCreated {
            get {
                return ResourceManager.GetString("Admin_UserCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to create user: {0}.
        /// </summary>
        public static string Admin_CreateFailed {
            get {
                return ResourceManager.GetString("Admin_CreateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User [{0}] was deleted..
        /// </summary>
        public static string Admin_UserDeleted {
            get {
                return ResourceManager.GetString("Admin_UserDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user: {0}.
        /// </summary>
        public static string Admin_DeleteFailed {
            get {
                return ResourceManager.GetString("Admin_DeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User [{0}] was added to team [{1}]..
        /// </summary>
        public static string Admin_UserAddedToTeam {
            get {
                return ResourceManager.GetString("Admin_UserAddedToTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to assign team: {0}.
        /// </summary>
        public static string Admin_TeamAssignFailed {
            get {
                return ResourceManager.GetString("Admin_TeamAssignFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D core paths.
        /// </summary>
        public static string Settings_PathsHeader {
            get {
                return ResourceManager.GetString("Settings_PathsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E3D installation folder (install_dir).
        /// </summary>
        public static string Settings_InstallDirLabel {
            get {
                return ResourceManager.GetString("Settings_InstallDirLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. D:\AVEVA\Everything3D3.1.
        /// </summary>
        public static string Settings_InstallDirPlaceholder {
            get {
                return ResourceManager.GetString("Settings_InstallDirPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local project repository (projects_dir).
        /// </summary>
        public static string Settings_ProjectsDirLabel {
            get {
                return ResourceManager.GetString("Settings_ProjectsDirLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. D:\AVEVA\Projects\E3D3.1.
        /// </summary>
        public static string Settings_ProjectsDirPlaceholder {
            get {
                return ResourceManager.GetString("Settings_ProjectsDirPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global environment script (evars.bat).
        /// </summary>
        public static string Settings_EvarsLabel {
            get {
                return ResourceManager.GetString("Settings_EvarsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. D:\AVEVA\Everything3D3.1\evars.bat.
        /// </summary>
        public static string Settings_EvarsPlaceholder {
            get {
                return ResourceManager.GetString("Settings_EvarsPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E3D version label.
        /// </summary>
        public static string Settings_VersionLabel {
            get {
                return ResourceManager.GetString("Settings_VersionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. AVEVA Everything3D 3.1.
        /// </summary>
        public static string Settings_VersionPlaceholder {
            get {
                return ResourceManager.GetString("Settings_VersionPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client preferences.
        /// </summary>
        public static string Settings_PreferencesHeader {
            get {
                return ResourceManager.GetString("Settings_PreferencesHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start with Windows (keep the environment ready).
        /// </summary>
        public static string Settings_AutoStart {
            get {
                return ResourceManager.GetString("Settings_AutoStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_LanguageLabel {
            get {
                return ResourceManager.GetString("Settings_LanguageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto (follow Windows).
        /// </summary>
        public static string Settings_LanguageAuto {
            get {
                return ResourceManager.GetString("Settings_LanguageAuto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About SEP.
        /// </summary>
        public static string Settings_AboutHeader {
            get {
                return ResourceManager.GetString("Settings_AboutHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SEP · AVEVA E3D Smart Project Manager.
        /// </summary>
        public static string Settings_AboutTagline {
            get {
                return ResourceManager.GetString("Settings_AboutTagline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Architecture: C# .NET 10 (DirectWrite / Windows 11 Mica).
        /// </summary>
        public static string Settings_AboutArch {
            get {
                return ResourceManager.GetString("Settings_AboutArch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Design: professional &amp; minimal (Obsidian Deep &amp; Fluent 2.0).
        /// </summary>
        public static string Settings_AboutStyle {
            get {
                return ResourceManager.GetString("Settings_AboutStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 💾 Save &amp; apply settings.
        /// </summary>
        public static string Settings_SaveButton {
            get {
                return ResourceManager.GetString("Settings_SaveButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        public static string Settings_Saved {
            get {
                return ResourceManager.GetString("Settings_Saved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D – New standardised project.
        /// </summary>
        public static string Create_Header {
            get {
                return ResourceManager.GetString("Create_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code (2–5 chars).
        /// </summary>
        public static string Create_CodeLabel {
            get {
                return ResourceManager.GetString("Create_CodeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. PRJ.
        /// </summary>
        public static string Create_CodePlaceholder {
            get {
                return ResourceManager.GetString("Create_CodePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project name / description.
        /// </summary>
        public static string Create_NameLabel {
            get {
                return ResourceManager.GetString("Create_NameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. 200 kt/a ethylene plant.
        /// </summary>
        public static string Create_NamePlaceholder {
            get {
                return ResourceManager.GetString("Create_NamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project root folder.
        /// </summary>
        public static string Create_RootDirLabel {
            get {
                return ResourceManager.GetString("Create_RootDirLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clone configuration from an existing project.
        /// </summary>
        public static string Create_CloneCheckbox {
            get {
                return ResourceManager.GetString("Create_CloneCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 💡 The 000/ISO/DWG/MAC/PIC/DFLTS folder skeleton and evars.bat are generated automatically, and the project is registered in ProjectInfo.xml and projects.ini..
        /// </summary>
        public static string Create_Hint {
            get {
                return ResourceManager.GetString("Create_Hint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✨ Create project.
        /// </summary>
        public static string Create_Button {
            get {
                return ResourceManager.GetString("Create_Button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decommission &amp; Archive.
        /// </summary>
        public static string Decommission_Title {
            get {
                return ResourceManager.GetString("Decommission_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AVEVA E3D – Decommission &amp; cold archive.
        /// </summary>
        public static string Decommission_Header {
            get {
                return ResourceManager.GetString("Decommission_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Archive the project as a ZIP file (cold backup).
        /// </summary>
        public static string Decommission_ArchiveCheckbox {
            get {
                return ResourceManager.GetString("Decommission_ArchiveCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unregister from ProjectInfo.xml and projects.ini.
        /// </summary>
        public static string Decommission_UnregisterCheckbox {
            get {
                return ResourceManager.GetString("Decommission_UnregisterCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete the project folder from disk (dangerous).
        /// </summary>
        public static string Decommission_DeleteCheckbox {
            get {
                return ResourceManager.GetString("Decommission_DeleteCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Archive folder:.
        /// </summary>
        public static string Decommission_ArchiveDirLabel {
            get {
                return ResourceManager.GetString("Decommission_ArchiveDirLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 📦 Confirm decommission.
        /// </summary>
        public static string Decommission_Button {
            get {
                return ResourceManager.GetString("Decommission_Button", resourceCulture);
            }
        }
    }
}
